function skillsMember() {
  return [
    { skill: "JavaScript", level: "5" },
    { skill: "HTML", level: "4" },
    { skill: "CSS", level: "3" },
    { skill: "React", level: "4" },
    { skill: "Node.js", level: "4" },
    { skill: "Express.js", level: "3" },
    { skill: "MongoDB", level: "3" },
    { skill: "SQL", level: "3" },
    { skill: "Python", level: "4" },
    { skill: "Django", level: "3" },
    { skill: "Flask", level: "3" },
    { skill: "Java", level: "4" },
    { skill: "Spring", level: "3" },
    { skill: "C++", level: "3" },
    { skill: "C#", level: "3" },
    { skill: "Swift", level: "3" },
    { skill: "Objective-C", level: "3" },
    { skill: "Kotlin", level: "3" },
    { skill: "Flutter", level: "3" },
    { skill: "Dart", level: "3" },
    { skill: "Git", level: "4" },
    { skill: "AWS", level: "3" },
    { skill: "Azure", level: "3" },
    { skill: "GCP", level: "3" },
    { skill: "Heroku", level: "3" },
    { skill: "Netlify", level: "3" },
    { skill: "Vercel", level: "3" },
  ];
}